#!/bin/bash

# Quick test guide for shielded fees

echo "🧪 Testing Noctura Shielded Mode - Fee Configuration"
echo "======================================================"
echo ""
echo "Prerequisites:"
echo "✓ Wallet has at least 0.1 SOL and 1 NOC"
echo "✓ App is running (npm run dev)"
echo "✓ You are in shielded mode"
echo ""

echo "Step 1: Set Shield Fees (Admin Only)"
echo "------------------------------------"
echo "In browser console:"
echo '  window.debugApi.setShieldFees()'
echo "        .then(r => console.log("✅ Result:", r))"
echo "        .catch(e => console.error("❌ Error:", e))"
echo ""
echo "Expected: Signature returned, no errors"
echo ""

echo "Step 2: Deposit SOL into Shielded Pool"
echo "--------------------------------------"
echo "Amount: 0.1 SOL"
echo "Expected transaction:"
echo "  - Transfer 1: 0.1 SOL to vault"
echo "  - Transfer 2: 0.25 NOC to fee collector"
echo "  - No other transfers"
echo ""

echo "Step 3: Check Blockchain Explorer"
echo "---------------------------------"
echo "Transaction should show:"
echo "  Transfer 1: From wallet → Vault (0.1 SOL)"
echo "  Transfer 2: From wallet → Fee collector (0.25 NOC)"
echo ""
echo "Should NOT see:"
echo "  ✗ 0.00025 SOL/WSOL fee"
echo "  ✗ 100 NOC transfer"
echo "  ✗ Any other transfers"
echo ""

echo "Step 4: Transfer Shielded Amount"
echo "-------------------------------"
echo "Amount: 0.05 SOL to recipient address"
echo "Expected:"
echo "  - Split transaction: moves 0.05 SOL in pool"
echo "  - Withdraw transaction: 0.05 SOL to recipient + 0.25 NOC fee"
echo "  - Total recipient receives: 0.05 SOL"
echo "  - You pay: 0.25 NOC fee"
echo ""

echo "Step 5: Verify Recipient"
echo "-----------------------"
echo "Recipient should have:"
echo "  ✓ 0.05 SOL in transparent wallet (no privacy loss)"
echo "  ✗ NO access to your shielded notes"
echo "  ✗ NO information about sender"
echo ""

echo "If Everything Works:"
echo "====================
echo "✅ Fees are correct (0.25 NOC only)"
echo "✅ Privacy is preserved"
echo "✅ SOL transactions use native SOL (not WSOL)"
echo ""

echo "Troubleshooting:"
echo "================"
echo "❌ See 0.00025 SOL fee?"
echo "   → Call window.debugApi.setShieldFees() to disable percentage fees"
echo ""
echo "❌ See 100 NOC transfer for SOL deposit?"
echo "   → Old code, rebuild with: npm run build"
echo ""
echo "❌ setShieldFees() fails with 'not admin'?"
echo "   → You must be the program deployer/admin"
echo "   → Only admin can update on-chain fees"
echo ""
